### ISSUE TITLE
[Feature] Don't register listeners if certain flags are disabled

### ISSUE THREAD

**Issue by WoodenAxe** [t00thpick1/Residence#1]
I have been running a fork of Residence with some of the high-frequency event listeners disabled, specifically `BlockFromToEvent` and `BlockPistonExtendEvent`. Those checks take up a considerable amount of CPU usage on a server with a large number of residences (or a lot of piston contraptions) and I noticed a real performance benefit (based on plugin timings) by removing them altogether. The `PlayerMoveEvent` may have a large impact as well. Obviously improving their performance while still retaining their functionality is more desirable, but for servers that have these flags disabled anyway it may be a useful compromise.

**Comment by drtshock** [comment]
Could have listeners registered as they are needed. Like if a res is created that sets move to false, then register the move listener.

**Comment by t00thpick1** [comment]
This is planned, thankya
