### ISSUE TITLE
[Bug] Measuring Being Performed Incorrectly

### ISSUE THREAD

**Issue by clucky** [t00thpick1/Residence#29]
When Residence calculates the size of a selection, it does this incorrectly. Instead of measuring the range of the blocks (ie. x:0 - x:20 = 21), it measures the difference of the blocks (ie. x:0 - x:20 = 20). I have noticed this same issue on /res select cost (when using XSize, YSize, ZSize) as well as /res select size, in addition to the final cost calculation.

**Comment by t00thpick1** [comment]
Pretty sure this specifically fixed that: https://github.com/t00thpick1/Residence/commit/9be7e5ff34ebddd311f5a8c73ef5efbe1b4344bc

**Comment by clucky** [comment]
Oh, I'll check jenkins when I get home. I hadn't seen it had been updated with a new build.

**Comment by clucky** [comment]
Issue resolved in [Residence Dev Build 66](http://ci.drtshock.net/job/Residence/66/)
