### ISSUE TITLE
Spigot1.8 don't work properly.

### ISSUE THREAD

**Issue by jesusango** [t00thpick1/Residence#34]
In [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]:

Residences created sometimes stop working and people can use it as if it don't have protection. There is a issue of this version, in previous versions it didn't happen.

When a player try put a Armor Stand in a residence without permissions, it can put and the armor stand isn't consumes from his inventory.

Players without permissions can take items in armor stands -but can't quit the armor stand.

**Comment by Ne0nx3r0** [comment]
@t00thpick1 Are you planning to support the 1.8 Bukkit/Spigot builds?

**Comment by Kainzo** [comment]
I heard he is not.

**Comment by Ne0nx3r0** [comment]
I guess by default development is moving to:
http://www.spigotmc.org/resources/residence-reloaded-1-8.2697/

https://github.com/DartCZ/Residence
