### ISSUE TITLE
[Feature] Case insensitive residence names

### ISSUE THREAD

**Issue by WoodenAxe** [t00thpick1/Residence#4]
One problem we have is that people create a residence with a public teleport for a store named `/res tp Walmart` but then someone else creates a residence of `/res tp walmart` and creates a fall trap at that location. It would be useful if residence names were case insensitive.

**Comment by clucky** [comment]
I personally do not see any reason why Residence names should be case-sensitive, as it would create confusion for two residences to be named the same thing to begin with. More than likely, the residence that is the same name as another, but different capitalization, is a hoax or a scam. It would be in the best interest of the community for residence names to be case insensitive.

**Comment by t00thpick1** [comment]
Actually I already did this a while ago
